// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTDaBppQgzk6-Rx1y8dJGVZysEyrKKa0',
    appId: '1:971632461714:web:57675e66343e91a39aa34b',
    messagingSenderId: '971632461714',
    projectId: 'mugi-b14a4',
    authDomain: 'mugi-b14a4.firebaseapp.com',
    storageBucket: 'mugi-b14a4.appspot.com',
    measurementId: 'G-5WL0B8V61W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0uuSTxzpUYYqipGtBxAN2JP7CyNmeyfQ',
    appId: '1:971632461714:android:636d5e4b668afa6f9aa34b',
    messagingSenderId: '971632461714',
    projectId: 'mugi-b14a4',
    storageBucket: 'mugi-b14a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDe8o6t5WNk-ioFh6knq0uGHCCYuWHy5Ks',
    appId: '1:971632461714:ios:9517b761923fcbf69aa34b',
    messagingSenderId: '971632461714',
    projectId: 'mugi-b14a4',
    storageBucket: 'mugi-b14a4.appspot.com',
    iosBundleId: 'com.example.untitled',
  );
}
